### ISSUE TITLE
Local MediaStream drops out on iPhone 6

### ISSUE THREAD

**Issue by LinusU** [cloudwebrtc/flutter-webrtc#66] opened 2019-03-21 15:18 UTC
This can be seen in the example app, after connecting a call the local video on the iPhone 6 (and the remote video on the other device) disappears after ~1-2 seconds. Sometimes it comes back after a while, but then it also disappears a while after that...

Happy to provide any more information you might need!

**Comment by rostopira** [comment] 2019-03-21 16:16
Duplicate of #56 
I'm working on it currently

**Closed by rostopira** 2019-03-21 16:16 UTC

**Comment by LinusU** [comment] 2019-03-21 16:58
Sorry, that's great to hear though! Let me know if I can help in any way 🙌

**Comment by rostopira** [comment] 2019-03-21 17:01
Check out metal_experiment branch
Test
Debug
Fix
PR
??????? 
PROFIT
