### ISSUE TITLE
Not work in web

### ISSUE THREAD

**Issue by msaber2015** [cloudwebrtc/flutter-webrtc#244] opened 2020-04-30 23:12 UTC
**errors.dart:147 Uncaught (in promise) Error: Unable to getUserMedia: [object OverconstrainedError]
at Object.throw_ [as throw] (errors.dart:196)
at getUserMedia (get_user_media.dart:23)
at getUserMedia.throw ()
at onError (async_patch.dart:62)
at _RootZone.runBinary (zone.dart:1386)
at _FutureListener.thenAwait.handleError (future_impl.dart:154)
at handleError (future_impl.dart:694)
at Function._propagateToListeners (future_impl.dart:715)
at _Future.new.[_completeError] (future_impl.dart:534)
at async._AsyncCallbackEntry.new.callback (future_impl.dart:582)
at Object._microtaskLoop (schedule_microtask.dart:43)
at _startMicrotaskLoop (schedule_microtask.dart:52)
at async_patch.dart:168**

**Video call with mobile**

**open camera and initialize webrtc object **

**Web all  browser **

* **Flutter version: 1.15.4-pre.5**: 
* **Plugin version:0.2.8**:
* **WEB**: 
* **Win 10**:

**Comment by ycherniavskyi** [comment] 2020-05-01 10:07
@msaber2015, hm does not this issue duplicate your already reported issue #239?

**Comment by ycherniavskyi** [comment] 2020-05-06 12:40
Just compare provided stack trace, and yes this is duplicate of #239.

**Comment by ycherniavskyi** [comment] 2020-05-06 12:41
Duplicate of #239

**Closed by ycherniavskyi** 2020-05-06 12:41 UTC
