### ISSUE TITLE
Cant get MediaStream twice

### ISSUE THREAD

**Issue by CodeStrings** [cloudwebrtc/flutter-webrtc#61] opened 2019-02-08 19:14 UTC
Getting the MediaStream for the first time is no problem at all and adding it to a PeerConnection. The second time I add the same stream to another PeerConnection it says the Camera is already in Usage. Is there an Method to disable the camera? To dispose the Stream doesn't work out for me.

**Comment by CodeStrings** [comment] 2019-02-08 19:22
It Works Fine on Any device out of Android x86 with an Epson Moverio bt-300

**Comment by rostopira** [comment] 2019-02-09 11:09
Can you provide some sample code? I can't really understand what you are doing

**Comment by CodeStrings** [comment] 2019-02-09 11:24
@rostopira `Future<MediaStream> createStream() async {
    print("Getting Stream");

    if(_localStream != null) {
      return _localStream;
    }

    final Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth': '720',
          'minHeight': '480',
          'minFrameRate': '21'
        },
        'facingMode': 'environment'
      },
      'facingMode': 'environment',
      'optional': []
    };

    MediaStream stream = await navigator.getUserMedia(mediaConstraints);

    if(this.onLocalStream != null) {
      this.onLocalStream(stream);
    }

    return stream;
  }`
First time the Stream is getting created and added to a PeerConnection everything is fine. But the second time I try to connect it says the camera is already is used and the RTCVideoRenderer Image is also frozen after this action. But this doesn't make any sense to me, because it is the same stream...

**Comment by rostopira** [comment] 2019-02-09 11:41
Are you trying to establish multipeer connection? If yes, you should use single localStream object (hold it in static variable, dispose only when both connections are closed)
If not, I don't see, where you disposing localStream.

**Comment by CodeStrings** [comment] 2019-02-09 11:57
I assign it it _localStream and then return it if it is present. I already tried disposing it but the camera wasn't disabled for a strange reason.

**Comment by rostopira** [comment] 2019-02-09 12:06
Have you seen something strange in logcat? Some disposing errors?
And I didn't really understood, what is that:

> It Works Fine on Any device out of Android x86 with an Epson Moverio bt-300

**Comment by CodeStrings** [comment] 2019-02-09 12:20
Only error that is showing is that the camera is already in use. Android x86 is only supported by the debug version, but that shouldnt make a impact or?

**Comment by rostopira** [comment] 2019-02-09 12:32
Here is part of `GetUserMediaImpl` class
```java
    void removeVideoCapturer(String id) {
        VideoCapturer videoCapturer = mVideoCapturers.get(id);
        if (videoCapturer != null) {
            try {
                videoCapturer.stopCapture();
            } catch (InterruptedException e) {
                Log.e(TAG, "removeVideoCapturer() Failed to stop video capturer");
            }
            mVideoCapturers.remove(id);
        }
    }
```
That's why I'm asking for logcat, filter it and search for that message, if there is error in closing camera, print exceptions stack-trace and post it

> Android x86 is only supported by the debug version

Not really, x86 actually supported
It's blocked in build.gradle, to avoid stupid issues "OMG your plogin is brken, fix it ASAP" caused by bug in flutter build system
I'm going to replace it with more elegant solution to support any arch

**Comment by CodeStrings** [comment] 2019-02-09 13:55
Wait you say you can run a release Version. I couldnt find that could you please tell me how? Trying to get the Logs but the test device is not at my side right now, will try later this day.

**Comment by rostopira** [comment] 2019-02-09 14:28
Okay, if you really want to do so, I've commited workaround https://github.com/cloudwebrtc/flutter-webrtc/commit/7860e3baa7aa6159fc86c36ff76be38fe7e0f307
Flutter allows to build apk with only one arch, specified explicitly 
Try that
```bash
flutter run --release --target-platform=android-x86
```

**Comment by CodeStrings** [comment] 2019-02-09 14:38
Yeah thats why I was suprised. Im a little bit disappointed about that and I might even change to Ionic for this one ;(

**Comment by rostopira** [comment] 2019-02-21 10:23
Closing due to inactivity

**Closed by rostopira** 2019-02-21 10:23 UTC
Labels: question
