### ISSUE TITLE
Video Call Crash on Android with flutter v1.6.0

### ISSUE THREAD

**Issue by wbarnard** [cloudwebrtc/flutter-webrtc#97] opened 2019-05-23 02:57 UTC
Crashes on Android when trying to make a video call in my application, no crash with flutter versions <1.5.x. Have confirmed the crash also occurs with the demo app with v1.6.0 and not with v1.5.8.

Select option GetUserMedia in demo app.

Debug output:
```
W/System.err(16041): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: main
W/System.err(16041): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err(16041): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/System.err(16041): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
W/System.err(16041): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:151)
W/System.err(16041): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:144)
W/System.err(16041): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
W/System.err(16041): 	at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer$1.onFirstFrameRendered(FlutterRTCVideoRenderer.java:52)
W/System.err(16041): 	at com.cloudwebrtc.webrtc.SurfaceTextureRenderer.updateFrameDimensionsAndReportEvents(SurfaceTextureRenderer.java:126)
W/System.err(16041): 	at com.cloudwebrtc.webrtc.SurfaceTextureRenderer.onFrame(SurfaceTextureRenderer.java:98)
W/System.err(16041): 	at org.webrtc.NativeAndroidVideoTrackSource.nativeOnFrameCaptured(Native Method)
W/System.err(16041): 	at org.webrtc.NativeAndroidVideoTrackSource.onFrameCaptured(NativeAndroidVideoTrackSource.java:79)
W/System.err(16041): 	at org.webrtc.VideoSource$1.onFrameCaptured(VideoSource.java:82)
W/System.err(16041): 	at org.webrtc.CameraCapturer$2.onFrameCaptured(CameraCapturer.java:164)
W/System.err(16041): 	at org.webrtc.Camera2Session$CaptureSessionCallback.lambda$onConfigured$0(Camera2Session.java:209)
W/System.err(16041): 	at org.webrtc.-$$Lambda$Camera2Session$CaptureSessionCallback$UDvzHNj8-cAJE1WNByx98pxD9vA.onFrame(Unknown Source:2)
W/System.err(16041): 	at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:308)
W/System.err(16041): 	at org.webrtc.SurfaceTextureHelper.lambda$new$0(SurfaceTextureHelper.java:149)
W/System.err(16041): 	at org.webrtc.-$$Lambda$SurfaceTextureHelper$7YTfC0byyd0o_zI7mNhfP12Gm0Q.onFrameAvailable(Unknown Source:2)
W/System.err(16041): 	at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
W/System.err(16041): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(16041): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(16041): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/rtc     (16041): 
E/rtc     (16041): 
E/rtc     (16041): #
E/rtc     (16041): # Fatal error in: gen/sdk/android/generated_base_jni/jni/../../../../../../../../../usr/local/google/home/sakal/code/webrtc-aar-release/src/sdk/android/src/jni/jni_generator_helper.h, line 85
E/rtc     (16041): # last system error: 11
E/rtc     (16041): # Check failed: !env->ExceptionCheck()
E/rtc     (16041): # 
F/libc    (16041): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18312 (main), pid 16041 (c.webrtcexample)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/jackpotltexx/jackpotlte:9/PPR1.180610.011/A530FXXS5CSE4:user/release-keys'
Revision: '7'
ABI: 'arm64'
pid: 16041, tid: 18312, name: main  >>> com.cloudwebrtc.webrtcexample <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0  0000000000000000  x1  0000000000004788  x2  0000000000000006  x3  0000000000000008
    x4  31772f31321f2b37  x5  31772f31321f2b37  x6  31772f31321f2b37  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000083  x9  98c6b922ae86e789  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
    x16 0000007ee7d33290  x17 0000007ee7c726c8  x18 0000000000000001  x19 0000000000003ea9
    x20 0000000000004788  x21 0000000000000055  x22 0000007e4597dd07  x23 0000007e459a6ed3
    x24 0000000000000500  x25 0000007e27bff588  x26 0000007e49844ba0  x27 0000007e49844bc0
    x28 0000000000000000  x29 0000007e27bfbba0
    sp  0000007e27bfbb60  lr  0000007ee7c65ecc  pc  0000007ee7c65ef4
backtrace:
    #00 pc 0000000000021ef4  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000207a40  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #02 pc 000000000020484c  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #03 pc 000000000020477c  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #04 pc 00000000003b5110  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #05 pc 00000000003cf1d8  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #06 pc 00000000003c6748  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #07 pc 00000000003b03d4  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so
    #08 pc 00000000003b02f4  /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/lib/arm64/libjingle_peerconnection_so.so (Java_org_webrtc_NativeAndroidVideoTrackSource_nativeOnFrameCaptured+28)
    #09 pc 0000000000563be0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
    #10 pc 000000000055ae4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #11 pc 00000000000d04e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #12 pc 00000000002838c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #13 pc 000000000027e9ec  /system/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+748)
    #14 pc 000000000052cebc  /system/lib64/libart.so (MterpInvokeStaticRange+148)
    #15 pc 000000000054d614  /system/lib64/libart.so (ExecuteMterpImpl+15380)
    #16 pc 000000000004bdb4  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.NativeAndroidVideoTrackSource.onFrameCaptured+28)
    #17 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #18 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #19 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #20 pc 000000000052a1a8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #21 pc 000000000054d194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #22 pc 000000000005639e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.VideoSource$1.onFrameCaptured+162)
    #23 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #24 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #25 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #26 pc 000000000052b124  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #27 pc 000000000054d394  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #28 pc 000000000003cec2  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.CameraCapturer$2.onFrameCaptured+134)
    #29 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #30 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #31 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #32 pc 000000000052b124  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #33 pc 000000000054d394  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #34 pc 000000000003bdc8  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.Camera2Session$CaptureSessionCallback.lambda$onConfigured$0+216)
    #35 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #36 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #37 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #38 pc 000000000052b6ac  /system/lib64/libart.so (MterpInvokeStatic+204)
    #39 pc 000000000054d314  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #40 pc 000000000003808c  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.-$$Lambda$Camera2Session$CaptureSessionCallback$UDvzHNj8-cAJE1WNByx98pxD9vA.onFrame+4)
    #41 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #42 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #43 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #44 pc 000000000052b124  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #45 pc 000000000054d394  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #46 pc 000000000005383a  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame+210)
    #47 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #48 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #49 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #50 pc 000000000052b4e8  /system/lib64/libart.so (MterpInvokeDirect+296)
    #51 pc 000000000054d294  /system/lib64/libart.so (ExecuteMterpImpl+14484)
    #52 pc 000000000005347e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.SurfaceTextureHelper.lambda$new$0+6)
    #53 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #54 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #55 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #56 pc 000000000052b6ac  /system/lib64/libart.so (MterpInvokeStatic+204)
    #57 pc 000000000054d314  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #58 pc 0000000000038334  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.cloudwebrtc.webrtcexample-J5JwYmqm5jHaIiQBfBsyNA==/base.apk_16041_16041 (deleted) (org.webrtc.-$$Lambda$SurfaceTextureHelper$7YTfC0byyd0o_zI7mNhfP12Gm0Q.onFrameAvailable+4)
    #59 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #60 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #61 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #62 pc 000000000052b124  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #63 pc 000000000054d394  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #64 pc 0000000000565890  /system/framework/boot-framework.vdex (android.graphics.SurfaceTexture$1.handleMessage+8)
    #65 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #66 pc 000000000025d0c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #67 pc 000000000027d8ac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #68 pc 000000000052a1a8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #69 pc 000000000054d194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #70 pc 0000000000c6219e  /system/framework/boot-framework.vdex (android.os.Handler.dispatchMessage+42)
    #71 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #72 pc 000000000051aa3c  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #73 pc 0000000000563cfc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #74 pc 000000000000df80  /dev/ashmem/dalvik-jit-code-cache_16041_16041 (deleted) (android.os.Looper.loop+1200)
    #75 pc 000000000055ae4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #76 pc 00000000000d04e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #77 pc 00000000002838c0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #78 pc 000000000027d8c8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #79 pc 000000000052b6ac  /system/lib64/libart.so (MterpInvokeStatic+204)
    #80 pc 000000000054d314  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #81 pc 0000000000c61ce0  /system/framework/boot-framework.vdex (android.os.HandlerThread.run+56)
    #82 pc 00000000002575cc  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.989670283+488)
    #83 pc 000000000051aa3c  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #84 pc 0000000000563cfc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #85 pc 000000000055ab88  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #86 pc 00000000000d04c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #87 pc 00000000004618ac  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #88 pc 0000000000462968  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    #89 pc 000000000048dd88  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
    #90 pc 0000000000083650  /system/lib64/libc.so (__pthread_start(void*)+196)
    #91 pc 0000000000023b34  /system/lib64/libc.so (__start_thread+68)
Lost connection to device.
```

Tested on Android v9.0 & v8.0.

Flutter version: 1.6.0
Plugin version: 0.1.7

**Comment by cloudwebrtc** [comment] 2019-05-23 05:53
Duplicate of #87 .

**Comment by cloudwebrtc** [comment] 2019-05-24 05:50
Fixed https://github.com/cloudwebrtc/flutter-webrtc/commit/a15119730e3f4652fdf4451333ab2a11a9ebaade

**Closed by cloudwebrtc** 2019-05-24 05:50 UTC
